from models.analytical.multi_occupation_multi_isotope import MultiOccupationMultiIsotope
from models.analytical.single_occupation_single_isotope import SingleOccupationSingleIsotope
from models.analytical.trap_diffusion import TrapDiffusion, hadamard